name: scm-pipeline
channels:
  - conda-forge
dependencies:
  - python >=3.13
  - lsstdesc-ceci
  - pygraphviz
  # - pip:
  #     - git+https://github.com/Roman-HLIS-Cosmology-PIT/psf-pipeline
  #     - git+https://github.com/Roman-HLIS-Cosmology-PIT/pyimcom
  #     - git+https://github.com/Roman-HLIS-Cosmology-PIT/roman-hlis-l2-driver
  #     - git+https://github.com/Roman-HLIS-Cosmology-PIT/metadetect-driver
  #     - git+https://github.com/Roman-HLIS-Cosmology-PIT/imcom-pipeline
  #     - git+https://github.com/Roman-HLIS-Cosmology-PIT/shear-pipeline
