name: scm-pipeline
channels:
  - conda-forge
dependencies:
  - python >=3.13
  - lsstdesc-ceci
  - pip:
      - git+https://github.com/Roman-HLIS-Cosmology-PIT/imcom-pipeline.git
      - git+https://github.com/Roman-HLIS-Cosmology-PIT/psf-pipeline.git
      - git+https://github.com/Roman-HLIS-Cosmology-PIT/scm-pipeline.git
      - git+https://github.com/Roman-HLIS-Cosmology-PIT/shear-pipeline.git
