# Python modules that are imported to find
# stage classes.  Any stages imported in these
# modules are automatically detected and their names can
# be used below
modules: psf_pipeline imcom_pipeline roman_sompz

# The launcher to use
# These are defined in ceci/sites
launcher:
    name: mini

site:
    name: local
    max_threads: 4


# The list of stages to run and the number of processors
# to use for each.
stages:
    # psf-pipeline
    - name: DetectionStage
      nprocess: 1
    - name: SelectionStage
      nprocess: 1
    - name: ColorAssignmentStage
      nprocess: 1
    - name: FittingStage
      nprocess: 1

    # imcom-pipeline
    - name: ConfigConversion
      nprocess: 1
    - name: Destripe
      nprocess: 1
    - name: PSFSplit
      nprocess: 1
    - name: BuildLayers
      nprocess: 1
    - name: ImcomInitial
      nprocess: 1
    - name: imsubtract
      nprocess: 1
    - name: ImcomFinal
      nprocess: 1
    - name: GenerateOutputs
      nprocess: 1

    # shear-pipeline
    # - name: metadetect
    #   nprocess: 1

# Definitions of where to find inputs for the overall pipeline.
# Any input required by a pipeline stage that is not generated by
# a previous stage must be defined here.  They are listed by tag.
inputs:
    Exposure: /tmp/inputs/exposure.asdf
    sed_library: /tmp/
    manifest_file1: /tmp/index1.txt


# Overall configuration file 
config: ./config.yaml

# If all the outputs for a stage already exist then do not re-run that stage
resume: True

# Put all the output files in this directory:
output_dir: ./outputs

# Put the logs from the individual stages in this directory:
log_dir: ./logs

